JPP3_PATH = r'X:\SteamLibrary\steamapps\common\The Jackbox Party Pack 3'
JPP4_PATH = r'X:\SteamLibrary\steamapps\common\The Jackbox Party Pack 4'
JPP5_PATH = r'X:\SteamLibrary\steamapps\common\The Jackbox Party Pack 5'
JPP6_PATH = r'X:\SteamLibrary\steamapps\common\The Jackbox Party Pack 6'
JPP7_PATH = r'X:\SteamLibrary\steamapps\common\The Jackbox Party Pack 7'
TJSP_PATH = r'X:\SteamLibrary\steamapps\common\The Jackbox Party Starter'
QUIPLASH2_PATH = r'X:\SteamLibrary\steamapps\common\Quiplash 2 InterLASHional'
DRAWFUL2_PATH = r'X:\SteamLibrary\steamapps\common\Drawful 2'

JPP3_RELEASE_PATH = r'X:\Jackbox\games\jpp3\jackbox-pack-3'
JPP4_RELEASE_PATH = r'X:\Jackbox\games\jpp4\jackbox-pack-4'
JPP6_RELEASE_PATH = r'X:\Jackbox\games\jpp6\jackbox-pack-6'
JPP7_RELEASE_PATH = r'X:\Jackbox\games\jpp7\jackbox-pack-7'
TJSP_RELEASE_PATH = r'X:\Jackbox\games\tjsp\jackbox-pack-starter'
