PATH = r'C:\Program Files (x86)\Steam\steamapps\common\The Jackbox Party Pack 4\games\SurviveTheInternet'
PATH_TWIST = PATH + r'\content\STITwist.jet'
PATH_DESKTOP_FOLDER = PATH + r'\content\STIDesktopFolderName.jet'
PATH_WARNING = PATH + r'\content\STIWarningGag.jet'
PATH_MESSENGER = PATH + r'\content\STIMessengerGag.jet'
PATH_ADDRESS_BAR = PATH + r'\content\STIAddressBarGag.jet'
PATH_NAME = PATH + r'\content\STIName.jet'
PATH_THEME_INTRO = PATH + r'\content\STIThemeIntro.jet'

# encoded
PATH_EXPANDED = r'data/pp3/fakin/swf/FakinIt_Expanded.json'
PATH_AUDIO_SUBTITLES = r'data/pp3/fakin/swf/audio_subtitles.json'
PATH_TASKS_ENCODED = r'data/pp3/fakin/encoded/tasks.json'
PATH_CATEGORIES_ENCODED = r'data/pp3/fakin/encoded/categories.json'
PATH_INPUT_ENCODED = r'data/pp3/fakin/encoded/input.json'
PATH_LEADERBOARDS_ENCODED = r'data/pp3/fakin/encoded/leaderboards.json'
PATH_SETTINGS_ENCODED = r'data/pp3/fakin/encoded/settings.json'
