PATH = r'C:\Program Files (x86)\Steam\steamapps\common\The Jackbox Party Pack 4\games\MonsterMingle'
PATH_MONSTER = PATH + r'\content\MMMonster.jet'
PATH_AUDIENCE_ANSWER = PATH + r'\content\MMMonsterAudienceAnswer.jet'
PATH_AUDIENCE_QUESTION = PATH + r'\content\MMMonsterAudienceQuestion.jet'
PATH_NPC = PATH + r'\content\MMMonsterNpc.jet'
PATH_NPC_ANSWER = PATH + r'\content\MMMonsterNpcAnswer.jet'
PATH_SECRET_WORDS = PATH + r'\content\MMSecretWords.jet'
PATH_SPONSORS = PATH + r'\content\MMSponsors.jet'

# encoded
PATH_EXPANDED = r'data/pp3/fakin/swf/FakinIt_Expanded.json'
PATH_AUDIO_SUBTITLES = r'data/pp3/fakin/swf/audio_subtitles.json'
PATH_TASKS_ENCODED = r'data/pp3/fakin/encoded/tasks.json'
PATH_CATEGORIES_ENCODED = r'data/pp3/fakin/encoded/categories.json'
PATH_INPUT_ENCODED = r'data/pp3/fakin/encoded/input.json'
PATH_LEADERBOARDS_ENCODED = r'data/pp3/fakin/encoded/leaderboards.json'
PATH_SETTINGS_ENCODED = r'data/pp3/fakin/encoded/settings.json'
