PATH = r'C:\Program Files (x86)\Steam\steamapps\common\Quiplash 2 InterLASHional'
PATH_QUESTIONS = PATH + r'\content\QuiplashQuestion'
PATH_QUESTIONS_JSON = PATH + r'\content\QuiplashQuestion.jet'
PATH_RELEASE = r'C:\Users\админ\Desktop\Jackbox\Quiplash 2\jackbox-quiplash2-ua'
PATH_BACKUP = r'C:\Users\админ\Desktop\Jackbox\Quiplash 2\backup'
PATH_BACKUP_QUESTIONS_JSON = PATH_BACKUP + r'\content\QuiplashQuestion.jet'
