# encoded
PATH = r'C:\Program Files (x86)\Steam\steamapps\common\The Jackbox Party Starter\games\triviadeath2'
PATH_EN = PATH + r'\content\en'
PATH_QUIPLASH = PATH_EN + r'\QuiplashContent.jet'
PATH_DICTATION = PATH_EN + r'\TDDictation.jet'
PATH_SEQUEL = PATH_EN + r'\TDSequel.jet'
PATH_MIRROR_TUTORIAL = PATH_EN + r'\TDMirrorTutorial.jet'
PATH_MIRROR = PATH_EN + r'\TDMirror.jet'
PATH_MIND_MELD = PATH_EN + r'\TDMindMeld.jet'
PATH_QUESTION = PATH_EN + r'\TDQuestion.jet'
PATH_QUESTION_HAT = PATH_EN + r'\TDQuestionHat.jet'
PATH_QUESTION_WIG = PATH_EN + r'\TDQuestionWig.jet'
PATH_QUESTION_GHOST = PATH_EN + r'\TDQuestionGhost.jet'
PATH_QUESTION_MADNESS = PATH_EN + r'\TDQuestionMadness.jet'
PATH_QUESTION_KNIFE = PATH_EN + r'\TDQuestionKnife.jet'
PATH_QUESTION_BOMB = PATH_EN + r'\TDQuestionBomb.jet'
PATH_FINAL_ROUND = PATH_EN + r'\TDFinalRound.jet'
PATH_WORDLIST_RULES = PATH + r'\wordlistRules_en.txt'
# dirs
PATH_QUESTION_DIR = PATH_EN + r'\TDQuestion'
PATH_FINAL_ROUND_DIR = PATH_EN + r'\TDFinalRound'

# encoded
PATH_DATA = '../data/tjsp/tmp2/'
PATH_ENCODED_QUIPLASH = PATH_DATA + r'encoded/EncodedTMP2QuiplashContent.json'
PATH_ENCODED_DICTATION = PATH_DATA + r'encoded/EncodedTMP2Dictation.json'
PATH_ENCODED_SEQUEL = PATH_DATA + r'encoded/EncodedTDSequel.json'
PATH_ENCODED_QUESTION = PATH_DATA + r'encoded/EncodedQuestion.json'
PATH_TRANSLATED_DICT = PATH_DATA + r'swf/translated_dict.txt'
PATH_SOURCE_DICT = PATH_DATA + r'swf/dict.txt'
PATH_EDITABLE_DICT = PATH_DATA + r'swf/editable.txt'

# release
PATH_RELEASE = r'~\Desktop\Jackbox\starter-pack\jackbox-starter-pack-ua'

# build
PATH_BUILD = '../build/uk/TMP2/'
PATH_BUILD_GAME = '../build/uk/TMP2/in-game/'
PATH_BUILD_QUIPLASH = PATH_BUILD_GAME + r'EncodedTMP2QuiplashContent.json'
PATH_BUILD_DICTATION = PATH_BUILD_GAME + r'EncodedTMP2Dictation.json'
PATH_BUILD_SEQUEL = PATH_BUILD_GAME + r'EncodedTDSequel.json'
PATH_BUILD_MIRROR = PATH_BUILD_GAME + r'mirror.json'
PATH_BUILD_MIRROR_TUTORIAL = PATH_BUILD_GAME + r'mirror_tutorial.json'
PATH_BUILD_MIND_MELD = PATH_BUILD_GAME + r'mind_meld.json'
PATH_BUILD_QUESTION = PATH_BUILD_GAME + r'EncodedQuestion.json'
PATH_BUILD_QUESTION_HAT = PATH_BUILD_GAME + r'EncodedQuestionHat.json'
PATH_BUILD_QUESTION_WIG = PATH_BUILD_GAME + r'EncodedQuestionWig.json'
PATH_BUILD_QUESTION_GHOST = PATH_BUILD_GAME + r'question_ghost.json'
PATH_BUILD_QUESTION_MADNESS = PATH_BUILD_GAME + r'question_madness.json'
PATH_BUILD_QUESTION_KNIFE = PATH_BUILD_GAME + r'question_knife.json'
PATH_BUILD_QUESTION_BOMB = PATH_BUILD_GAME + r'question_bomb.json'
PATH_BUILD_FINAL_ROUND = PATH_BUILD_GAME + r'final_questions.json'
PATH_BUILD_WORDLIST_RULES = PATH_BUILD_GAME + r'wordlistRules_en.txt'
PATH_AUDIO = PATH_BUILD + r'EncodedAudio.json'
PATH_SUBTITLES = PATH_BUILD_GAME + r'text_subtitles.json'
