# encoded
PATH = r'C:\Program Files (x86)\Steam\steamapps\common\The Jackbox Party Starter\games\triviadeath2'
PATH_EN = PATH + r'\content\en'
PATH_QUIPLASH = PATH_EN + r'\QuiplashContent.jet'
PATH_DICTATION = PATH_EN + r'\TDDictation.jet'
PATH_SEQUEL = PATH_EN + r'\TDSequel.jet'
PATH_MIRROR_TUTORIAL = PATH_EN + r'\TDMirrorTutorial.jet'
PATH_MIRROR = PATH_EN + r'\TDMirror.jet'
PATH_MIND_MELD = PATH_EN + r'\TDMindMeld.jet'
PATH_QUESTION = PATH_EN + r'\TDQuestion.jet'
PATH_QUESTION_HAT = PATH_EN + r'\TDQuestionHat.jet'
PATH_QUESTION_WIG = PATH_EN + r'\TDQuestionWig.jet'
PATH_QUESTION_GHOST = PATH_EN + r'\TDQuestionGhost.jet'
PATH_QUESTION_MADNESS = PATH_EN + r'\TDQuestionMadness.jet'
PATH_QUESTION_KNIFE = PATH_EN + r'\TDQuestionKnife.jet'
PATH_QUESTION_BOMB = PATH_EN + r'\TDQuestionBomb.jet'
PATH_FINAL_ROUND = PATH_EN + r'\TDFinalRound.jet'
PATH_WORDLIST_RULES = PATH + r'\wordlistRules_en.txt'
# dirs
PATH_QUESTION_DIR = PATH_EN + r'\TDQuestion'
PATH_FINAL_ROUND_DIR = PATH_EN + r'\TDFinalRound'

# encoded
PATH_ENCODED_QUIPLASH = 'data/tmp2/EncodedTMP2QuiplashContent.json'
PATH_ENCODED_DICTATION = 'data/tmp2/EncodedTMP2Dictation.json'
PATH_ENCODED_SEQUEL = 'data/tmp2/EncodedTDSequel.json'
PATH_ENCODED_QUESTION = 'data/tmp2/EncodedQuestion.json'

# release
PATH_RELEASE = r'~\Desktop\Jackbox\starter-pack\jackbox-starter-pack-ua'

# build
PATH_BUILD_QUIPLASH = 'build/uk/TMP2/in-game/EncodedTMP2QuiplashContent.json'
PATH_BUILD_DICTATION = 'build/uk/TMP2/in-game/EncodedTMP2Dictation.json'
PATH_BUILD_SEQUEL = 'build/uk/TMP2/in-game/EncodedTDSequel.json'
PATH_BUILD_MIRROR = 'build/uk/TMP2/in-game/mirror.json'
PATH_BUILD_MIRROR_TUTORIAL = 'build/uk/TMP2/in-game/mirror_tutorial.json'
PATH_BUILD_MIND_MELD = 'build/uk/TMP2/in-game/mind_meld.json'
PATH_BUILD_QUESTION = 'build/uk/TMP2/in-game/EncodedQuestion.json'
PATH_BUILD_QUESTION_HAT = 'build/uk/TMP2/in-game/EncodedQuestionHat.json'
PATH_BUILD_QUESTION_WIG = 'build/uk/TMP2/in-game/EncodedQuestionWig.json'
PATH_BUILD_QUESTION_GHOST = 'build/uk/TMP2/in-game/question_ghost.json'
PATH_BUILD_QUESTION_MADNESS = 'build/uk/TMP2/in-game/question_madness.json'
PATH_BUILD_QUESTION_KNIFE = 'build/uk/TMP2/in-game/question_knife.json'
PATH_BUILD_QUESTION_BOMB = 'build/uk/TMP2/in-game/question_bomb.json'
PATH_BUILD_FINAL_ROUND = 'build/uk/TMP2/in-game/final_questions.json'
PATH_BUILD_WORDLIST_RULES = 'build/uk/TMP2/in-game/wordlistRules_en.txt'
